### ISSUE TITLE
Metadata mode not supported for pid=arXiv:2302.00338

### ISSUE THREAD

**Issue by asajedi** [FC4E-WP5/metaresolver-handletemplate#12]
`curl -X "GET"  "https://apimr.devel.argo.grnet.gr/v1/metaresolvers/resolve?pidMode=metadat&redirect=true&pid=arXiv:2302.00338" -H "accept: application/json"`

`{"code":400,"message":"This mode {metadat} is not supported."}`

**Comment by themiszamani** [comment]
@asajedi  I think the problem is that you write metadat and not metadata. 
Could you please check again?

**Comment by asajedi** [comment]
@themiszamani I copied the url from somewhere and you are right, there is a typo in the url. So the issue can be closed.

**Comment by asajedi** [comment]
Resolved
